# Rubocop configuration file

# Code complexity metrics are tracked separately for lib/ vs. tests/
# See lib/.rubocop.yml and tests/.rubocop.yml

# Baseline code complexity metrics - we should try and reduce these over time
Metrics/AbcSize:
  Enabled: true

Metrics/CyclomaticComplexity:
  Enabled: true

Metrics/MethodLength:
  Enabled: true

Metrics/PerceivedComplexity:
  Enabled: true

# Team preferences different from Rubocop defaults:
Metrics/ClassLength:
  Enabled: false

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/ClassCheck:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

Style/TrivialAccessors:
  AllowPredicates: true
